# Generated by Django 5.1.1 on 2024-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
