# Generated by Django 5.1.1 on 2024-09-28 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_website", "0003_education_internship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Education",
        ),
    ]
