# Generated by Django 5.1.1 on 2024-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_website", "0004_delete_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
