# Generated by Django 5.1.1 on 2024-09-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio_website",
            "0005_project_skills_alter_project_title_alter_skill_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
